export const GET_NOTIFICATION_REQUEST="GET_NOTIFICATION_REQUEST"
export const GET_NOTIFICATION_SUCCESS="GET_NOTIFICATION_SUCCESS"
export const GET_NOTIFICATION_FAIL="GET_NOTIFICATION_FAIL"

export const GET_NOTIFICATIONS_REQUEST="GET_NOTIFICATIONS_REQUEST"
export const GET_NOTIFICATIONS_SUCCESS="GET_NOTIFICATIONS_SUCCESS"
export const GET_NOTIFICATIONS_FAIL="GET_NOTIFICATIONS_FAIL"

export const NOTIFICATION_RECIEVED='NOTIFICATION_RECEIVED';
export const NOTIFICATION_READ='NOTIFICATION_READ'
export const NOTIFICATION_CLEAR='NOTIFICATION_CLEAR'