
export const GET_TRIPS_REQUEST="GET_TRIPS_REQUEST"
export const GET_TRIPS_SUCCESS="GET_TRIPS_SUCCESS"
export const GET_TRIPS_FAIL="GET_TRIPS_FAIL"


export const GET_TRIP_REQUEST="GET_TRIP_REQUEST"
export const GET_TRIP_SUCCESS="GET_TRIP_SUCCESS"
export const GET_TRIP_FAIL="GET_TRIP_FAIL"


export const GET_USER_TRIP_REQUEST="GET_USER_TRIP_REQUEST"
export const GET_USER_TRIP_SUCCESS="GET_USER_TRIP_SUCCESS"
export const GET_USER_TRIP_FAIL="GET_USER_TRIP_FAIL"

export const ADD_PASSENGER_REQUEST="ADD_PASSENGER_REQUEST"
export const ADD_PASSENGER_SUCCESS="ADD_PASSENGER_SUCCESS"
export const ADD_PASSENGER_FAIL="ADD_PASSENGER_FAIL"


export const CANCEL_TRIP_REQUEST="CANCEL_TRIP_REQUEST"
export const CANCEL_TRIP_SUCCESS="CANCEL_TRIP_SUCCESS"
export const CANCEL_TRIP_FAIL="CANCEL_TRIP_FAIL"

export const SEND_DATA_TO_API='SEND_DATA_TO_API'